[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = {version = "0.5.1", features = ["secrets","json"]}
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
argon2 = "0.5.3"
rusqlite = "0.37.0"
dotenv = "0.15.0"
base64 = "0.22.1"